### ISSUE TITLE
System Latency + Framedrops

### ISSUE THREAD

**Issue by Jtonna** [LukenSkyne/Valorant-Match-Spy#5]
I've noticed that leaving this running while my match is going results in significant system latency issues + frame drops. I've reproduced the issue on a separate system as well.

system input + render latency goes from 5-8 ms to 20-30ms and my framerate goes from 400 to about 150-200.

I'm curious if anyone else is able to reproduce my observations. If so could this be caused by some sort of application state being refreshed every time the API is queried and if so what is the polling rate?

**Comment by RXJpaw** [comment]
Please state system information for your tested hardware. I can't reproduce this issue with neither Ryzen 5 2600, 1660 SUPER nor Ryzen 5 7600X, 1080 Ti

**Comment by RXJpaw** [comment]
Please also provide following information, aside from system stats:
- CPU/Disk/GPU usage of the process
- Used Anti-Virus Software

**Comment by LukenSkyne** [comment]
Sounds strange. I haven't had any performance hits even when the tool was running for 3+ hours.

There isn't any polling that is happening on a regular basis. The app is connecting to a websocket server which is hosted by the game.

What does happen every now and then are presence updates (friendlist etc.). I'm not sure if an anti-virus might affect the delivery of these events (scanning the traffic for example), but you can try to disable it and see if anything changes.

**Comment by Jtonna** [comment]
5800x, 32gb ram, 3070ti.
the other system is a 3600x, 1070ti & 16gb ram. 

Malwarebytes is on both systems but doesn't run in the background.

I can't see GPU usage as I'm running a modified version of windows from https://www.revi.cc/ for better system performance. (both systems running this, so this could be the issue. Ill reinstall default windows and compare shortly)

If it makes a difference I'm not running in dev mode I'm running the compiled version. I also notice there's an Update Available notification in the app,  i doubt querying it often would result in the issue but does it re-query the version often?

these are the settings in val i used to reproduce the issue.
![image](https://user-images.githubusercontent.com/34466548/213839611-f401a55a-4607-4b88-97ab-a776708091ed.png)

Here is the performance in task manager
![image](https://user-images.githubusercontent.com/34466548/213839726-a36010f4-8db9-434f-986b-bc813bbc4a66.png)

**Comment by RXJpaw** [comment]
This problem is related to the use of Valorant Match Spy but not caused by it, looking at provided information. Since you're not using regular Windows we will not be able to tell you if some (f.e. Anti-Virus) Software of your custom Windows Build inflicts drops in performance. 

Tested on 2 Windows 10 and 2 Windows 11 Systems, this issue cannot be reproduced.
Please provide further information when trying to run Valorant Match Spy on a clean Windows installation.

**Comment by LukenSkyne** [comment]
The version is only queried on startup. The "current version" is not present in the source code since it is supplied through a deployment script, but you could update the version [here](https://github.com/LukenSkyne/Valorant-Match-Spy/blob/main/internal/utils/self-updater.go#L16) and try setting it to something >=1.4.5

**Comment by Jtonna** [comment]
No worries. Feel free to close the issue and ill reopen it over the weekend if I can reproduce it on a clean win10 install.
Ill also provide a video of the said issue if I can reproduce it on a clean install.

Appreciate the support
